name: test 

on:
    pull_request: 
        branches:
            - main

jobs:
    test:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: set up python 3.10.12
              uses: actions/setup-python@v5.4.0
              with:
                    python-version: 3.10.12
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Test with pytest
              run: |
                pytest --exitfirst
              

    